modLoader="javafml"
loaderVersion="[25,)"
license="GNU GPL 3.0"
issueTrackerURL="https://example.invalid/"
logoFile="icon-chn_500.png"

[[mods]]
modId="neb"
version="${file.jarVersion}"
displayName="Not Enough Bandwidth"
description=""
authors="USS_Shenzhou, Burning_TNT"

[[dependencies.neb]]
modId="minecraft"
mandatory=true
versionRange="[1.18, 1.19)"